### ISSUE TITLE
Activate Travis

### ISSUE THREAD

**Issue by richelbilderbeek** [olli0601/rBEAST#5]
I have added a Travis CI build script, but it is rather useless if Travis is not activated.

To activate Travis:
- go to [http://www.travis-ci.org](http://www.travis-ci.org)
- signs in with GitHub
- Go to 'Accounts' 
- Activate 'rBEAST' by clicking the slider

I'd volunteer if I could, but this can only be done by @olli0601

**Comment by olli0601** [comment]
Thanks - this is now activated. Best wishes, olli
