### ISSUE TITLE
Beast Treeannotator output file not opening

### ISSUE THREAD

**Issue by avvypaks** [olli0601/rBEAST#6]
I am using "beast2out.read.nexus.and.stats"  function to read the output file of Treeannotator (.tre file). Its showing : 
Error in data.table(NEXUS_ID = sapply(tmp, "[[", 1), NEXUS_LABEL = sapply(tmp,  : 
  could not find function "data.table"

Can I use this function as an alternative to "read.beast" ?? I am getting an error in the phyloch package for this.

**Comment by richelbilderbeek** [comment]
Hi @avvypaks, I respond as (1) maybe @olli0601 does not have notification enabled, (2) I may be able to redirect you to the answer, as I have had adopted part of this repo's code.

I am unsure, but I guess rBEAST relies on older versions of packages (as you can see [in the commits](https://github.com/olli0601/rBEAST/commits/master), it has not been maintained for 5 years). 

Maybe I can do a shameless plug for [the tracerer package](https://github.com/ropensci/tracerer) can help you out, which is a package that is actively maintained.

**Comment by avvypaks** [comment]
Thanks for the reply.
I am trying to run "https://raw.githubusercontent.com/taming-the-beast/FBD-tutorial/master/scripts/plot_geoscaled_tree.R" this script. The annotated .tre file from "Treeannotator" contains some necessary information like "node height" which can not be loaded in R by "read.nexus" command. 
Can you help me out with this? Which function can I use in the "tracerer package" to load my annotated tree into R?

**Comment by richelbilderbeek** [comment]
Hi @avvypaks, I can sure try to help you out. For that I need the file you want to load. Could you upload it? Also, a reprex (Google!) usually helps others to help you better.

**Comment by avvypaks** [comment]
Certainly. I am attaching my .tre file here.
I have used the "treeio" package which has the "read.beast" function. Its is loading the tree with all necessary information. 
But after running the code 
"t$root.time <- t$height[1]"

its showing :
Error in t$height : $ operator not defined for this S4 class.


[withoutoutgrp.zip](https://github.com/olli0601/rBEAST/files/5900044/withoutoutgrp.zip)

**Comment by richelbilderbeek** [comment]
Thanks, I see now! Sadly, this is not a regular BEAST2 posterior `.trees ` file, so `tracerer` cannot read it. Maybe the `treeio` people can help you out :+1:

```r
# Fails
tracerer::parse_beast_trees("withoutoutgrp.tre")
```

**Comment by avvypaks** [comment]
Yes. treeio is parsing the file. But 
`t$root.time <- t$height[1]`
code is not working in this script:  https://raw.githubusercontent.com/taming-the-beast/FBD-tutorial/master/scripts/plot_geoscaled_tree.R

**Comment by richelbilderbeek** [comment]
Like I said,

> Maybe the treeio people can help you out +1

I think that is where this problem belongs and where other people may enjoy to find it. When posting, it will be helpful to post a minimal reprex instead of linking to a full script. Good luck :+1:

**Comment by olli0601** [comment]
Hi both. Thanks @richelbilderbeek -- the rBEAST code is indeed no longer maintained. Better to go with tracerer or similar efforts :-)

Good luck!

**Comment by avvypaks** [comment]
Thanks for your reply !!
